server:
  port: 9090

app:
  cors:
    origin: http://localhost:3000
    method: GET,POST,PUT,DELETE,OPTIONS
    header: "*"
  auth:
    key: ${AUTH_KEY:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347440}
    exp: ${AUTH_EXP:3600} # Default expire after 1 hour
  integration:
    health_buddy_be:
      url: ${HEALTH_BUDDY_BE:http://localhost:3000}

spring:
  application:
    name: hospital-mgmt
  mvc:
    log-request-details: true
  datasource:
    url: ${POSTGRES_URL:}
    username: ${POSTGRES_USERNAME:}
    password: ${POSTGRES_PASSWORD:}
#    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/health_buddy}
#    username: ${POSTGRES_USERNAME:admin}
#    password: ${POSTGRES_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

logging:
  level:
    web: ${LOG_LEVEL:info} # trace for local
  structured:
    format:
      console: ${LOG_FORMAT:} # ecs for prod

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: b3_multi
      produce: b3_multi
      consume: b3_multi